// COUNTRY DROPDOWN MENU
export const AFRICAN_COUNTRIES = [
  'Nigeria',
  'Ethiopia',
  'Egypt',
  'DR Congo',
  'Tanzania',
  'South Africa',
  'Kenya',
  'Uganda',
  'Sudan',
  'Algeria',
  'Morocco',
  'Angola',
  'Ghana',
  'Mozambique',
  'Madagascar',
  "Côte d'Ivoire",
  'Cameroon',
  'Niger',
  'Mali',
  'Burkina Faso',
  'Malawi',
  'Zambia',
  'Chad',
  'Somalia',
  'Senegal',
  'Zimbabwe',
  'Guinea',
  'Rwanda',
  'Benin',
  'Burundi',
  'Tunisia',
  'South Sudan',
  'Togo',
  'Sierra Leone',
  'Libya',
  'Congo',
  'Central African Republic',
  'Liberia',
  'Mauritania',
  'Eritrea',
  'Gambia',
  'Botswana',
  'Namibia',
  'Gabon',
  'Lesotho',
  'Guinea-Bissau',
  'Equatorial Guinea',
  'Mauritius',
  'Eswatini',
  'Djibouti',
  'Comoros',
  'Cabo Verde',
  'Sao Tome & Principe',
  'Seychelles',
];
