const ERROR_STATUS_CODE: any = [400, 406];
const FORBIDDEN_ERROR_CODE: any = [401, 403];
const HIVE_ACCOUNT_EMAIL: string = 'hive-account-email';

export { ERROR_STATUS_CODE, FORBIDDEN_ERROR_CODE, HIVE_ACCOUNT_EMAIL };
